### ISSUE TITLE
Add GCPBackendPolicy to Gateway to avoid exposing services accidentally

### ISSUE THREAD

**Issue by pascalwhoop** [everycure-org/matrix#268]
Given this thread

https://www.googlecloudcommunity.com/gc/Google-Kubernetes-Engine-GKE/IaP-not-on-by-default-for-HTTPRoute-amp-public-Gateway-how-to/m-p/795896#M2341

We should set a policy like so
```
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: backend-policy
spec:
  default:
    iap:
      enabled: true
      oauth2ClientSecret:
        name: SECRET_NAME
      clientID: CLIENT_ID
  targetRef:
    group: ""
    kind: Service
    name: lb-service
```

To ensure no service gets publicly exposed by accident

This is a FUP of #211
