### ISSUE TITLE
Refactor and rename catalog entries to remove kedro layers and instead group by pipeline

### ISSUE THREAD

**Issue by pascalwhoop** [everycure-org/matrix#461]
# Refactor Data Catalog naming convention and folder structure

## Current Situation
Our current Data Catalog uses a naming convention of `<pipeline>.<layer>.<name>` for
dataset entries, with corresponding folder structure in `globals.yml` using numbered
prefixes (e.g., `01_raw`, `02_intermediate`, etc.). This structure is often confusing
and is not serving the way we think about our datasets as grouped by the pipeline in
which they are produced.

## Motivation for Change
1. Simplify naming convention: The current three-level structure can be overly complex and redundant in some cases.
2. Enhance clarity: A simpler structure will make it easier for new team members to understand and navigate our data pipeline as well as the data residing in the storage buckets.
3. Reduce maintenance overhead: Simplifying the structure will make it easier to manage and update our Data Catalog as the project evolves.

## Proposed Change
We propose to refactor our Data Catalog naming convention to a two-level structure:
`<pipeline_name>.<dataset_name>`. This change will be reflected in both the
`catalog.yml` files and the folder structure defined in `globals.yml`.

## Completion Criteria
1. Update all `catalog.yml` files to use the new `<pipeline_name>.<dataset_name>` convention.
2. Refactor `globals.yml` to use pipeline-based paths instead of numbered layer paths. For example:
   ```yaml
   paths:
     raw: ${gcs_bucket}/data/raw
     ingestion: ${gcs_bucket}/data/ingestion
     integration: data/integration
     preprocessing: data/preprocessing
     embeddings: data/embeddings
     modelling: data/modelling
     evaluation: data/evaluation
     matrix_generation: data/matrix_generation
     reporting: data/reporting
     tmp: data/tmp
   ```
3. Update all pipeline code to reference datasets using the new naming convention.
4. Update any documentation or comments that reference the old naming convention.
5. Ensure all tests pass with the new structure.
6. Update `README.md` or other relevant documentation to explain the new naming convention and folder structure.

## Additional Notes
- This change will require careful coordination as it affects multiple parts of our codebase.
- We should consider doing this in a time where few people work on datasets & help
    people port their working branches to the new setup

## Questions to Consider
- How will this change affect our data versioning strategy?
    - likely not at all because we group all data under runs/releases and thus anything
        underneath that grouping is irrelevant to versioning
- Are there any external systems or scripts that depend on the current naming convention that will need to be updated?
