### ISSUE TITLE
Create a "stable workloads" label for kubernetes nodes, assign stable workload namespaces with node affinity

### ISSUE THREAD

**Issue by pascalwhoop** [everycure-org/matrix#839]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

1. Node Selectors:

```
kubectl label nodes <node-name> role=specific
```
(do this in terraform of course, not on a node)

2.	Set a default nodeSelector for the namespace:

```
apiVersion: v1
kind: Namespace
metadata:
  name: example-namespace
spec:
  nodeSelector:
    role: specific

```
Right now we create these namespaces automatically with ArgoCD. We should thus make sure
that is not automatic but we control that. E.g. in app-of-apps or in each application
templates folder  

Alternatively, you can set a nodeSelector in a pod’s spec:

spec:
  nodeSelector:
    role: specific

Note this only works for individual pods. We want to just assign a whole deployment
(e.g. observability) to a node

**Additional context**
