### ISSUE TITLE
Consider renaming OBJECT_KW to start with an underscore.

### ISSUE THREAD

**Issue by matwasilewski** [everycure-org/matrix#845]
**Is your feature request related to a problem? Please describe.**

Our `inject.py` code that is responsible for dependency injection has a set of static keywords defined. Arguments with those keywords will be converted to object at runtime, which allows us to define objects in `.yml` files and have them initialised at runtime.

```python
import re
from types import BuiltinFunctionType, FunctionType
from typing import Any, Dict, List, Tuple

OBJECT_KW = "object"
INSTANTIATE_KW = "instantiate"
UNPACK_KW = "unpack"
ENABLE_REGEXABLE_KWARG = "enable_regex"

logger = logging.getLogger(__file__)


def _load_obj(obj_path: str, default_obj_path: str = None) -> Any:
    """Extract an object from a given path.
```

During PR review https://github.com/everycure-org/matrix/pull/811 it was raised that we should rename this keyword (as well as possibly other keywords) to start with underscore. 

This would mean that all of our .yaml files that define `object:`, eg:

```yml
# Threshold-based classification metrics for ground truth data (clinical trials version)
evaluation.simple_classification_trials:
  evaluation_options:
    generator:
      object: matrix.datasets.pair_generator.GroundTruthTestPairs
      positive_columns: 
        - "trial_sig_better"
        - "trial_non_sig_better"
      negative_columns:
```

would also have to change to use `_object` keyword.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
